-- Insert sample island data
INSERT INTO islands (name, slug, description, short_description, location, coordinates, area_km2, population, best_time_to_visit, main_image_url, cultural_info, regulatory_info, visa_requirements, currency, languages, climate_info, featured) VALUES

('Santorini', 'santorini', 'Santorini is a volcanic island in the Cyclades group of the Greek islands. Famous for its dramatic cliffs, stunning sunsets, and distinctive blue-domed churches, Santorini offers a perfect blend of natural beauty and rich history. The island''s unique landscape was shaped by a massive volcanic eruption around 1600 BC, creating the iconic caldera that defines its coastline today.', 'A volcanic paradise famous for stunning sunsets and blue-domed churches', 'Cyclades, Greece', '{"lat": 36.3932, "lng": 25.4615}', 90.69, 15550, 'April to October', '/placeholder.svg?height=600&width=800', 'Rich in ancient Greek history with Minoan ruins at Akrotiri. Traditional Cycladic architecture with whitewashed buildings and blue accents. Famous for local wines produced from volcanic soil.', 'Part of the European Union. Standard EU regulations apply. No special permits required for most activities.', 'EU citizens: No visa required. Non-EU: Check Schengen visa requirements', 'EUR', '["Greek", "English"]', 'Mediterranean climate with hot, dry summers and mild winters. Average summer temperature: 25-28°C', true),

('Bali', 'bali', 'Bali, the Island of the Gods, is Indonesia''s most famous destination, known for its forested volcanic mountains, iconic rice paddies, beaches, and coral reefs. The island has a rich cultural heritage with thousands of Hindu temples, traditional arts, and vibrant ceremonies. From the cultural heart of Ubud to the beach clubs of Seminyak, Bali offers diverse experiences for every traveler.', 'The Island of the Gods with temples, rice terraces, and pristine beaches', 'Indonesia', '{"lat": -8.3405, "lng": 115.0920}', 5780, 4225000, 'April to October (dry season)', '/placeholder.svg?height=600&width=800', 'Predominantly Hindu culture with over 20,000 temples. Famous for traditional arts including batik, wood carving, and dance. Strong emphasis on spiritual harmony and community ceremonies.', 'Visa on arrival available for many countries. Respect local customs and dress codes at temples. Environmental protection laws in place.', 'Many countries eligible for visa-free or visa on arrival (30 days)', 'IDR', '["Indonesian", "Balinese", "English"]', 'Tropical climate with wet season (November-March) and dry season (April-October). Average temperature: 26-28°C year-round', true),

('Maldives', 'maldives', 'The Maldives is a tropical paradise consisting of 1,192 coral islands grouped into 26 atolls. Known for crystal-clear turquoise waters, pristine white sand beaches, and luxurious overwater bungalows, it''s a premier destination for honeymooners and luxury travelers. The islands offer world-class diving and snorkeling with vibrant coral reefs and diverse marine life.', 'A tropical paradise of coral islands with crystal-clear waters', 'Indian Ocean', '{"lat": 3.2028, "lng": 73.2207}', 298, 540544, 'November to April (dry season)', '/placeholder.svg?height=600&width=800', 'Islamic culture with strong maritime traditions. Local Dhivehi culture emphasizes community and respect for the ocean. Traditional music, dance, and crafts reflect the island heritage.', 'Islamic republic with strict alcohol and pork restrictions outside resorts. Environmental protection is crucial - coral reef conservation laws apply.', 'Visa on arrival for most countries (30 days)', 'MVR', '["Dhivehi", "English"]', 'Tropical monsoon climate. Dry season: November-April. Wet season: May-October. Average temperature: 26-30°C', true),

('Maui', 'maui', 'Maui, the second-largest Hawaiian island, is renowned for its diverse landscapes ranging from the sacred Haleakala volcano to the lush rainforests of Hana. The island offers world-famous beaches, the scenic Road to Hana, and incredible snorkeling at Molokini Crater. Maui perfectly balances adventure and relaxation with its rich Polynesian culture and modern amenities.', 'Hawaiian island with volcanic landscapes and the famous Road to Hana', 'Hawaii, USA', '{"lat": 20.7984, "lng": -156.3319}', 1883, 164221, 'April to May, September to November', '/placeholder.svg?height=600&width=800', 'Rich Polynesian and Hawaiian culture with traditional hula, luau celebrations, and respect for the land (aloha aina). Strong emphasis on ohana (family) and community values.', 'US state regulations apply. Marine life protection laws. Cultural site preservation requirements. Reef-safe sunscreen mandatory.', 'US citizens: No visa required. International visitors: Check US visa requirements', 'USD', '["English", "Hawaiian"]', 'Tropical climate with trade winds. Dry season: April-October. Wet season: November-March. Temperature: 21-29°C', true),

('Seychelles', 'seychelles', 'Seychelles is an archipelago of 115 islands in the Indian Ocean, famous for its pristine beaches, giant tortoises, and unique granite rock formations. The islands boast some of the world''s most photographed beaches, including Anse Source d''Argent. With exceptional biodiversity and luxury resorts, Seychelles offers an exclusive tropical getaway.', 'An archipelago paradise with granite boulders and pristine beaches', 'Indian Ocean', '{"lat": -4.6796, "lng": 55.4920}', 459, 98462, 'April to May, October to November', '/placeholder.svg?height=600&width=800', 'Creole culture blending African, French, and British influences. Three official languages reflect diverse heritage. Strong conservation ethic and respect for nature.', 'No visa required for most countries (up to 30 days). Strict environmental protection laws. Coco de mer export restrictions apply.', 'Visa-free for most countries (30 days)', 'SCR', '["Seychellois Creole", "English", "French"]', 'Tropical oceanic climate. Cooler season: May-September. Warmer season: October-April. Temperature: 24-30°C', true);
