-- Insert comprehensive island data
INSERT INTO islands (
  id,
  name,
  slug,
  location,
  short_description,
  description,
  main_image_url,
  featured,
  best_time_to_visit,
  area_km2,
  population,
  languages,
  currency,
  climate_info,
  cultural_info,
  regulatory_info,
  visa_requirements,
  coordinates,
  gallery_images
) VALUES 
(
  gen_random_uuid(),
  'Maldives Paradise',
  'maldives-paradise',
  'Indian Ocean',
  'Crystal clear waters and pristine beaches',
  'The Maldives is a tropical paradise consisting of 1,192 coral islands grouped in 26 atolls. Known for its crystal-clear turquoise waters, pristine white sand beaches, and luxurious overwater bungalows, it offers an unparalleled tropical experience.',
  '/maldives-paradise-beach.png',
  true,
  'November to April (dry season)',
  298,
  540544,
  '["Dhivehi", "English"]',
  'Maldivian Rufiyaa (MVR)',
  'Tropical monsoon climate with year-round temperatures between 26-30°C. Two distinct seasons: dry season (November-April) with less rainfall and northeast monsoons, and wet season (May-October) with southwest monsoons and higher humidity.',
  'Islamic culture with strong maritime traditions. Local customs include traditional music (boduberu), fishing practices, and handicrafts. Respect for Islamic values is essential - modest dress outside resorts, no public displays of affection, and alcohol only in licensed resorts.',
  'Strict environmental protection laws. No fishing in protected areas, coral collection prohibited, waste disposal regulations enforced. Resort islands have specific guidelines for water sports and marine activities.',
  'Tourist visa on arrival for most nationalities (30 days free). Valid passport required (minimum 6 months validity). No specific vaccinations required but hepatitis A/B and typhoid recommended.',
  '{"lat": 3.2028, "lng": 73.2207}',
  '["/maldives-1.jpg", "/maldives-2.jpg", "/maldives-3.jpg"]'
),
(
  gen_random_uuid(),
  'Bora Bora Lagoon',
  'bora-bora-lagoon',
  'French Polynesia',
  'Iconic overwater bungalows and volcanic peaks',
  'Bora Bora is a small South Pacific island surrounded by a lagoon and a barrier reef. Famous for its dramatic volcanic peaks, luxury resorts, and stunning overwater bungalows, it represents the ultimate romantic getaway destination.',
  '/bora-bora-overwater-bungalows.png',
  true,
  'May to October (dry season)',
  30.55,
  10605,
  '["French", "Tahitian", "English"]',
  'CFP Franc (XPF)',
  'Tropical climate with warm temperatures year-round (24-30°C). Dry season (May-October) has less humidity and rainfall. Wet season (November-April) brings higher temperatures, humidity, and occasional tropical storms.',
  'Polynesian culture with French influences. Traditional practices include tattooing, dance (otea), and crafts. Strong connection to nature and ocean. French colonial heritage evident in cuisine and architecture. Respect for Polynesian customs and environmental conservation is important.',
  'Protected marine environment with strict fishing regulations. Lagoon activities regulated to protect coral reefs. Import restrictions on certain items. Environmental fees may apply for certain activities.',
  'No visa required for stays under 90 days for most nationalities. Valid passport required. No mandatory vaccinations but hepatitis A/B, typhoid, and Japanese encephalitis recommended for some travelers.',
  '{"lat": -16.5004, "lng": -151.7415}',
  '["/bora-bora-1.jpg", "/bora-bora-2.jpg", "/bora-bora-3.jpg"]'
),
(
  gen_random_uuid(),
  'Santorini Cliffs',
  'santorini-cliffs',
  'Cyclades, Greece',
  'Dramatic cliffs and stunning sunsets',
  'Santorini is a volcanic island in the Cyclades known for its dramatic cliffs, whitewashed buildings, and spectacular sunsets. The island offers a unique blend of ancient history, distinctive architecture, and world-renowned wines.',
  '/santorini-cliffs-sunset.png',
  true,
  'April to October (warm and dry)',
  96,
  15550,
  '["Greek", "English"]',
  'Euro (EUR)',
  'Mediterranean climate with hot, dry summers (25-35°C) and mild winters (10-15°C). Best weather April-October with minimal rainfall. Strong winds (meltemi) common in summer. UV levels high due to reflection from white buildings.',
  'Greek Orthodox culture with ancient Cycladic traditions. Local customs include afternoon siesta, late dining, and strong family values. Traditional architecture with blue-domed churches and cave houses. Wine culture deeply rooted in volcanic soil viticulture.',
  'Archaeological site protections in place. Building restrictions maintain traditional architecture. Cruise ship limitations during peak season. Waste management regulations due to limited resources.',
  'EU citizens need valid ID. Non-EU visitors need passport (no visa required for stays under 90 days for most nationalities). No specific health requirements but travel insurance recommended.',
  '{"lat": 36.3932, "lng": 25.4615}',
  '["/santorini-1.jpg", "/santorini-2.jpg", "/santorini-3.jpg"]'
);
