-- Insert sample hotels for each island
INSERT INTO hotels (island_id, name, description, star_rating, coordinates, address, image_url, gallery_images, amenities, room_types, price_range, booking_url, affiliate_id, website_url, phone, email, rating, review_count) VALUES

-- Santorini Hotels
((SELECT id FROM islands WHERE slug = 'santorini'), 'Canaves Oia Suites', 'Luxury suites carved into the volcanic cliffs of Oia, offering breathtaking caldera views and world-class amenities. Each suite features a private terrace with infinity pool overlooking the Aegean Sea.', 5, '{"lat": 36.4618, "lng": 25.3753}', 'Oia, Santorini 84702, Greece', '/placeholder.svg?height=400&width=600', '[]', '["Infinity Pool", "Spa", "Fine Dining", "Concierge", "Airport Transfer", "WiFi", "Air Conditioning", "Private Terrace"]', '[{"type": "Superior Suite", "size": "45 sqm", "occupancy": 2, "price": 850}, {"type": "Premium Suite", "size": "65 sqm", "occupancy": 3, "price": 1200}]', '$$$$', 'https://booking.com/hotel/canaves-oia', 'SANT001', 'https://canaves.com', '+30 22860 71453', 'reservations@canaves.com', 4.8, 1247),

((SELECT id FROM islands WHERE slug = 'santorini'), 'Grace Hotel Santorini', 'Contemporary luxury hotel in Imerovigli with minimalist Cycladic design and panoramic caldera views. Features an award-winning spa and infinity pool.', 5, '{"lat": 36.4167, "lng": 25.4333}', 'Imerovigli, Santorini 84700, Greece', '/placeholder.svg?height=400&width=600', '[]', '["Infinity Pool", "Spa", "Fitness Center", "Restaurant", "Bar", "WiFi", "Air Conditioning", "Room Service"]', '[{"type": "Superior Room", "size": "35 sqm", "occupancy": 2, "price": 650}, {"type": "Suite", "size": "55 sqm", "occupancy": 3, "price": 950}]', '$$$$', 'https://booking.com/hotel/grace-santorini', 'SANT002', 'https://gracehotels.com', '+30 22860 20300', 'santorini@gracehotels.com', 4.7, 892),

((SELECT id FROM islands WHERE slug = 'santorini'), 'Villa Renos', 'Charming family-run hotel in Fira offering traditional Cycladic hospitality with modern comforts and stunning sea views at affordable prices.', 3, '{"lat": 36.4161, "lng": 25.4324}', 'Fira, Santorini 84700, Greece', '/placeholder.svg?height=400&width=600', '[]', '["Pool", "Restaurant", "WiFi", "Air Conditioning", "Balcony", "Airport Transfer"]', '[{"type": "Standard Room", "size": "25 sqm", "occupancy": 2, "price": 180}, {"type": "Superior Room", "size": "30 sqm", "occupancy": 3, "price": 220}]', '$$', 'https://booking.com/hotel/villa-renos', 'SANT003', 'https://villarenos.gr', '+30 22860 23848', 'info@villarenos.gr', 4.3, 456),

-- Bali Hotels
((SELECT id FROM islands WHERE slug = 'bali'), 'COMO Shambhala Estate', 'Luxury wellness retreat nestled in tropical rainforest, offering holistic healing experiences, yoga, and world-class spa treatments in harmony with nature.', 5, '{"lat": -8.5069, "lng": 115.2624}', 'Banjar Begawan, Payangan, Ubud, Bali 80571, Indonesia', '/placeholder.svg?height=400&width=600', '[]', '["Spa", "Yoga Studio", "Organic Restaurant", "Infinity Pool", "Fitness Center", "WiFi", "Air Conditioning", "Butler Service"]', '[{"type": "Terrace Suite", "size": "85 sqm", "occupancy": 2, "price": 1200}, {"type": "Garden Villa", "size": "120 sqm", "occupancy": 4, "price": 1800}]', '$$$$', 'https://booking.com/hotel/como-shambhala', 'BALI001', 'https://comohotels.com/shambhala', '+62 361 978888', 'res.shambhala@comohotels.com', 4.9, 678),

((SELECT id FROM islands WHERE slug = 'bali'), 'The Mulia Resort', 'Beachfront luxury resort in Nusa Dua featuring expansive suites, multiple pools, and award-winning dining with panoramic ocean views.', 5, '{"lat": -8.7833, "lng": 115.2167}', 'Jl. Raya Nusa Dua Selatan, Nusa Dua, Bali 80363, Indonesia', '/placeholder.svg?height=400&width=600', '[]', '["Beach Access", "Multiple Pools", "Spa", "Fine Dining", "Kids Club", "Golf Course", "WiFi", "Air Conditioning"]', '[{"type": "Ocean View Suite", "size": "72 sqm", "occupancy": 3, "price": 800}, {"type": "Presidential Suite", "size": "200 sqm", "occupancy": 6, "price": 2500}]', '$$$$', 'https://booking.com/hotel/mulia-resort', 'BALI002', 'https://themulia.com', '+62 361 3017777', 'reservation@themulia.com', 4.6, 1123),

((SELECT id FROM islands WHERE slug = 'bali'), 'Puri Garden Hotel', 'Boutique hotel in central Ubud surrounded by lush gardens, offering authentic Balinese hospitality and easy access to cultural attractions.', 3, '{"lat": -8.5069, "lng": 115.2624}', 'Jl. Monkey Forest Rd, Ubud, Bali 80571, Indonesia', '/placeholder.svg?height=400&width=600', '[]', '["Garden Pool", "Restaurant", "Spa", "WiFi", "Air Conditioning", "Bicycle Rental", "Cultural Tours"]', '[{"type": "Deluxe Room", "size": "32 sqm", "occupancy": 2, "price": 120}, {"type": "Garden Suite", "size": "45 sqm", "occupancy": 3, "price": 180}]', '$$', 'https://booking.com/hotel/puri-garden', 'BALI003', 'https://purigardenhotel.com', '+62 361 975719', 'info@purigardenhotel.com', 4.2, 789),

-- Maldives Hotels
((SELECT id FROM islands WHERE slug = 'maldives'), 'Soneva Fushi', 'Eco-luxury resort on a pristine island featuring overwater and beachfront villas, world-class dining, and sustainable luxury experiences.', 5, '{"lat": 5.2833, "lng": 73.0833}', 'Kunfunadhoo Island, Baa Atoll, Maldives', '/placeholder.svg?height=400&width=600', '[]', '["Overwater Villas", "Private Beach", "Spa", "Observatory", "Organic Garden", "Water Sports", "WiFi", "Air Conditioning"]', '[{"type": "Beach Villa", "size": "410 sqm", "occupancy": 4, "price": 2200}, {"type": "Water Villa", "size": "280 sqm", "occupancy": 3, "price": 3500}]', '$$$$', 'https://booking.com/hotel/soneva-fushi', 'MALD001', 'https://soneva.com/fushi', '+960 660 0304', 'reservations.fushi@soneva.com', 4.9, 567),

((SELECT id FROM islands WHERE slug = 'maldives'), 'Conrad Maldives Rangali Island', 'Iconic resort featuring the world''s first undersea restaurant and luxurious overwater villas connected by a bridge across two islands.', 5, '{"lat": 3.9167, "lng": 72.8333}', 'Rangali Island, Alif Dhaal Atoll, Maldives', '/placeholder.svg?height=400&width=600', '[]', '["Undersea Restaurant", "Overwater Spa", "Multiple Restaurants", "Water Sports", "Dolphin Watching", "WiFi", "Air Conditioning"]', '[{"type": "Beach Villa", "size": "150 sqm", "occupancy": 3, "price": 1800}, {"type": "Water Villa", "size": "125 sqm", "occupancy": 2, "price": 2800}]', '$$$$', 'https://booking.com/hotel/conrad-rangali', 'MALD002', 'https://conradmaldives.com', '+960 668 0629', 'rangali.reservations@conradhotels.com', 4.8, 934),

-- Maui Hotels
((SELECT id FROM islands WHERE slug = 'maui'), 'Grand Wailea Resort', 'Luxury beachfront resort featuring elaborate pools, world-class spa, and championship golf course with stunning ocean views.', 4, '{"lat": 20.6900, "lng": -156.4400}', '3850 Wailea Alanui Dr, Wailea, HI 96753, USA', '/placeholder.svg?height=400&width=600', '[]', '["Beach Access", "Multiple Pools", "Spa", "Golf Course", "Fine Dining", "Kids Activities", "WiFi", "Air Conditioning"]', '[{"type": "Ocean View Room", "size": "40 sqm", "occupancy": 4, "price": 650}, {"type": "Suite", "size": "85 sqm", "occupancy": 6, "price": 1200}]', '$$$', 'https://booking.com/hotel/grand-wailea', 'MAUI001', 'https://grandwailea.com', '+1 808 875 1234', 'reservations@grandwailea.com', 4.4, 2156),

((SELECT id FROM islands WHERE slug = 'maui'), 'Mama''s Fish House Inn', 'Charming beachfront inn adjacent to the famous Mama''s Fish House restaurant, offering intimate accommodations with authentic Hawaiian charm.', 3, '{"lat": 20.9167, "lng": -156.3333}', '799 Poho Pl, Paia, HI 96779, USA', '/placeholder.svg?height=400&width=600', '[]', '["Beach Access", "Restaurant", "Garden", "WiFi", "Air Conditioning", "Kitchenette"]', '[{"type": "Garden Room", "size": "35 sqm", "occupancy": 2, "price": 380}, {"type": "Oceanfront Room", "size": "40 sqm", "occupancy": 3, "price": 480}]', '$$$', 'https://booking.com/hotel/mamas-fish-house', 'MAUI002', 'https://mamasfishhouse.com', '+1 808 579 8488', 'inn@mamasfishhouse.com', 4.6, 445),

-- Seychelles Hotels
((SELECT id FROM islands WHERE slug = 'seychelles'), 'Four Seasons Resort Seychelles', 'Luxury hillside resort with private villas overlooking pristine beaches, featuring world-class spa and dining experiences.', 5, '{"lat": -4.3667, "lng": 55.8167}', 'Petite Anse, Baie Lazare, Mahé, Seychelles', '/placeholder.svg?height=400&width=600', '[]', '["Private Beach", "Spa", "Infinity Pool", "Fine Dining", "Water Sports", "Kids Club", "WiFi", "Air Conditioning"]', '[{"type": "Hillside Villa", "size": "95 sqm", "occupancy": 3, "price": 1400}, {"type": "Beachfront Villa", "size": "120 sqm", "occupancy": 4, "price": 2000}]', '$$$$', 'https://booking.com/hotel/four-seasons-seychelles', 'SEYC001', 'https://fourseasons.com/seychelles', '+248 4 393 000', 'reservations.seychelles@fourseasons.com', 4.7, 678),

((SELECT id FROM islands WHERE slug = 'seychelles'), 'Coral Strand Smart Choice Hotel', 'Beachfront hotel on Beau Vallon Beach offering comfortable accommodations, local cuisine, and easy access to water activities at great value.', 3, '{"lat": -4.6167, "lng": 55.4333}', 'Beau Vallon, Mahé, Seychelles', '/placeholder.svg?height=400&width=600', '[]', '["Beach Access", "Pool", "Restaurant", "Bar", "Water Sports", "WiFi", "Air Conditioning"]', '[{"type": "Standard Room", "size": "28 sqm", "occupancy": 2, "price": 220}, {"type": "Superior Room", "size": "35 sqm", "occupancy": 3, "price": 280}]', '$$', 'https://booking.com/hotel/coral-strand', 'SEYC002', 'https://coralstrand.sc', '+248 4 291 000', 'reservations@coralstrand.sc', 4.1, 892);
