-- Insert comprehensive hotel data
INSERT INTO hotels (
  id,
  island_id,
  name,
  description,
  image_url,
  star_rating,
  rating,
  review_count,
  price_range,
  amenities,
  room_types,
  address,
  phone,
  email,
  website_url,
  booking_url,
  coordinates,
  gallery_images
) VALUES 
-- Maldives Hotels
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  'Aqua Paradise Resort',
  'Luxury overwater villas with direct lagoon access, world-class spa, and pristine coral reef for snorkeling.',
  '/aqua-paradise-resort.jpg',
  5,
  4.8,
  1247,
  '$800-2000',
  '["Overwater Villas", "Spa", "Diving Center", "Fine Dining", "Private Beach", "Infinity Pool", "Water Sports", "Butler Service"]',
  '["Overwater Villa", "Beach Villa", "Presidential Suite"]',
  'North Male Atoll, Maldives',
  '+960 664-2345',
  'reservations@aquaparadise.mv',
  'https://aquaparadise.mv',
  'https://booking.com/aqua-paradise',
  '{"lat": 4.1755, "lng": 73.5093}',
  '["/aqua-1.jpg", "/aqua-2.jpg", "/aqua-3.jpg"]'
),
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  'Coral Bay Boutique',
  'Intimate boutique resort with personalized service, excellent snorkeling, and sustainable practices.',
  '/coral-bay-boutique.jpg',
  4,
  4.6,
  892,
  '$400-800',
  '["Boutique Experience", "Snorkeling", "Eco-Friendly", "Spa", "Restaurant", "Bar", "Kayaking", "Fishing"]',
  '["Beach Bungalow", "Garden Villa", "Honeymoon Suite"]',
  'South Male Atoll, Maldives',
  '+960 664-3456',
  'info@coralbay.mv',
  'https://coralbay.mv',
  'https://booking.com/coral-bay',
  '{"lat": 3.8456, "lng": 73.3821}',
  '["/coral-1.jpg", "/coral-2.jpg", "/coral-3.jpg"]'
),
-- Bora Bora Hotels
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  'Lagoon View Resort',
  'Iconic overwater bungalows with glass floor panels, Mount Otemanu views, and Polynesian cultural experiences.',
  '/lagoon-view-resort.jpg',
  5,
  4.9,
  2156,
  '$1200-3000',
  '["Overwater Bungalows", "Glass Floor Panels", "Spa", "Cultural Shows", "Water Sports", "Fine Dining", "Private Beach", "Helicopter Tours"]',
  '["Overwater Bungalow", "Beach Suite", "Royal Villa"]',
  'Bora Bora, French Polynesia',
  '+689 40 60 78 90',
  'reservations@lagoonview.pf',
  'https://lagoonview.pf',
  'https://booking.com/lagoon-view',
  '{"lat": -16.4895, "lng": -151.7314}',
  '["/lagoon-1.jpg", "/lagoon-2.jpg", "/lagoon-3.jpg"]'
),
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  'Polynesian Paradise',
  'Authentic Polynesian experience with traditional fare, cultural activities, and stunning lagoon views.',
  '/polynesian-paradise.jpg',
  4,
  4.7,
  1543,
  '$600-1200',
  '["Traditional Architecture", "Cultural Activities", "Lagoon Views", "Restaurant", "Bar", "Spa", "Kayaking", "Snorkeling"]',
  '["Garden Bungalow", "Lagoon View Room", "Family Suite"]',
  'Bora Bora, French Polynesia',
  '+689 40 67 89 12',
  'info@polynesianparadise.pf',
  'https://polynesianparadise.pf',
  'https://booking.com/polynesian-paradise',
  '{"lat": -16.5123, "lng": -151.7456}',
  '["/poly-1.jpg", "/poly-2.jpg", "/poly-3.jpg"]'
),
-- Santorini Hotels
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  'Cliffside Luxury Hotel',
  'Perched on the caldera cliffs with infinity pools, cave suites, and world-famous sunset views.',
  '/cliffside-luxury.jpg',
  5,
  4.8,
  1876,
  '$500-1500',
  '["Infinity Pool", "Cave Suites", "Sunset Views", "Spa", "Fine Dining", "Wine Cellar", "Concierge", "Private Terraces"]',
  '["Cave Suite", "Caldera View Room", "Honeymoon Villa"]',
  'Oia, Santorini, Greece',
  '+30 22860 71234',
  'reservations@cliffside.gr',
  'https://cliffside.gr',
  'https://booking.com/cliffside-luxury',
  '{"lat": 36.4618, "lng": 25.3753}',
  '["/cliff-1.jpg", "/cliff-2.jpg", "/cliff-3.jpg"]'
),
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  'Aegean Boutique Inn',
  'Charming traditional Cycladic architecture with modern amenities, wine tasting, and personalized service.',
  '/aegean-boutique.jpg',
  4,
  4.5,
  1234,
  '$200-600',
  '["Traditional Architecture", "Wine Tasting", "Rooftop Terrace", "Restaurant", "Spa", "Concierge", "Airport Transfer"]',
  '["Standard Room", "Superior Room", "Junior Suite"]',
  'Fira, Santorini, Greece',
  '+30 22860 72345',
  'info@aegeanboutique.gr',
  'https://aegeanboutique.gr',
  'https://booking.com/aegean-boutique',
  '{"lat": 36.4138, "lng": 25.4318}',
  '["/aegean-1.jpg", "/aegean-2.jpg", "/aegean-3.jpg"]'
);
