-- Insert comprehensive events data
INSERT INTO events (
  id,
  island_id,
  title,
  description,
  image_url,
  event_type,
  start_date,
  end_date,
  start_time,
  end_time,
  location,
  organizer,
  ticket_price,
  ticket_url,
  featured,
  contact_info,
  coordinates
) VALUES 
-- Maldives Events
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  'Sunset Beach Yoga',
  'Join us for a peaceful yoga session on pristine white sand beaches as the sun sets over the Indian Ocean. Suitable for all levels with certified instructors.',
  '/sunset-beach-yoga.png',
  'wellness',
  '2025-08-15',
  '2025-08-15',
  '18:00:00',
  '19:30:00',
  'Paradise Beach, North Male Atoll',
  'Maldives Wellness Center',
  25.00,
  'https://maldiveswellness.com/yoga',
  true,
  '{"phone": "+960 330-5678", "email": "yoga@maldiveswellness.com"}',
  '{"lat": 4.1755, "lng": 73.5093}'
),
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  'Underwater Snorkeling Adventure',
  'Explore vibrant coral reefs and tropical marine life in crystal-clear waters. Equipment provided, suitable for beginners and experienced snorkelers.',
  '/underwater-snorkeling.png',
  'adventure',
  '2025-08-20',
  '2025-08-20',
  '09:00:00',
  '12:00:00',
  'Coral Garden, South Male Atoll',
  'Ocean Adventures Maldives',
  75.00,
  'https://oceanadventures.mv/snorkeling',
  true,
  '{"phone": "+960 330-6789", "email": "adventures@oceanadventures.mv"}',
  '{"lat": 3.8456, "lng": 73.3821}'
),
-- Bora Bora Events
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  'Traditional Island Cooking Class',
  'Learn to prepare authentic Polynesian dishes using local ingredients. Includes market tour, cooking session, and feast with local families.',
  '/island-cooking-class.png',
  'cultural',
  '2025-08-25',
  '2025-08-25',
  '10:00:00',
  '15:00:00',
  'Vaitape Village, Bora Bora',
  'Polynesian Cultural Center',
  120.00,
  'https://polynesianculture.pf/cooking',
  true,
  '{"phone": "+689 40 67 12 34", "email": "cooking@polynesianculture.pf"}',
  '{"lat": -16.5123, "lng": -151.7456}'
),
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  'Luxury Catamaran Sunset Cruise',
  'Sail around the lagoon on a luxury catamaran with champagne, canapés, and breathtaking sunset views of Mount Otemanu.',
  '/catamaran-sunset-cruise.jpg',
  'luxury',
  '2025-08-30',
  '2025-08-30',
  '16:00:00',
  '19:00:00',
  'Bora Bora Lagoon',
  'Lagoon Cruises Polynesia',
  180.00,
  'https://lagooncruises.pf/sunset',
  true,
  '{"phone": "+689 40 60 78 90", "email": "cruises@lagooncruises.pf"}',
  '{"lat": -16.4895, "lng": -151.7314}'
),
-- Santorini Events
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  'Volcano Hiking Expedition',
  'Guided hike to the active volcano crater with geological insights, stunning views, and traditional Greek lunch in Thirassia.',
  '/volcano-hiking-expedition.png',
  'adventure',
  '2025-09-05',
  '2025-09-05',
  '08:00:00',
  '16:00:00',
  'Nea Kameni Volcano, Santorini',
  'Santorini Adventures',
  95.00,
  'https://santorini-adventures.gr/volcano',
  true,
  '{"phone": "+30 22860 71234", "email": "adventures@santorini-adventures.gr"}',
  '{"lat": 36.4018, "lng": 25.3956}'
),
(
  gen_random_uuid(),
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  'Marine Life Photography Workshop',
  'Professional underwater photography workshop in the Aegean Sea. Equipment provided, suitable for all skill levels.',
  '/underwater-marine-life-photography.png',
  'educational',
  '2025-09-10',
  '2025-09-10',
  '09:00:00',
  '17:00:00',
  'Kamari Beach, Santorini',
  'Aegean Photo Academy',
  150.00,
  'https://aegeanphoto.gr/workshop',
  true,
  '{"phone": "+30 22860 72345", "email": "workshop@aegeanphoto.gr"}',
  '{"lat": 36.3932, "lng": 25.4615}'
);
