-- Adding comprehensive island data with all required fields
INSERT INTO islands (
  id, name, slug, location, short_description, description, 
  best_time_to_visit, main_image_url, featured, climate_info, 
  cultural_info, regulatory_info, visa_requirements, currency,
  languages, population, area_km2, coordinates, gallery_images,
  created_at, updated_at
) VALUES 
(
  gen_random_uuid(),
  'Maldives Paradise',
  'maldives-paradise',
  'Indian Ocean',
  'Crystal clear waters and pristine beaches',
  'The Maldives offers an unparalleled tropical paradise experience with crystal-clear turquoise waters, pristine white sand beaches, and luxurious overwater bungalows.',
  'November to April',
  '/maldives-paradise-beach.png',
  true,
  'Tropical climate with temperatures ranging from 24-33°C year-round. Two distinct seasons: dry season (November-April) and wet season (May-October).',
  'Rich Islamic heritage with traditional dhoni boats, local fishing communities, and vibrant coral reef ecosystems. Respect for local customs is essential.',
  'Alcohol consumption restricted to resort islands. Modest dress required on local islands. Environmental protection laws strictly enforced.',
  'Tourist visa on arrival for most nationalities, valid for 30 days. Passport must be valid for at least 6 months.',
  'Maldivian Rufiyaa (MVR)',
  '["Dhivehi", "English"]',
  540000,
  298.0,
  '{"lat": 3.2028, "lng": 73.2207}',
  '["/maldives-1.jpg", "/maldives-2.jpg", "/maldives-3.jpg"]',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Bora Bora Lagoon',
  'bora-bora-lagoon',
  'French Polynesia',
  'Iconic overwater bungalows and volcanic peaks',
  'Bora Bora is renowned for its stunning lagoon, dramatic volcanic peaks, and world-class luxury resorts with iconic overwater bungalows.',
  'May to October',
  '/bora-bora-overwater-bungalows.png',
  true,
  'Tropical climate with temperatures 24-30°C. Dry season (May-October) and wet season (November-April). Trade winds provide natural cooling.',
  'Polynesian culture with traditional dance, music, and crafts. French colonial influence evident in cuisine and architecture.',
  'French territory laws apply. Environmental protection of lagoon strictly enforced. Respect for sacred sites required.',
  'No visa required for stays under 90 days for most nationalities. Valid passport required.',
  'CFP Franc (XPF)',
  '["French", "Tahitian", "English"]',
  10605,
  30.55,
  '{"lat": -16.5004, "lng": -151.7415}',
  '["/bora-bora-1.jpg", "/bora-bora-2.jpg", "/bora-bora-3.jpg"]',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Santorini Cliffs',
  'santorini-cliffs',
  'Greece, Aegean Sea',
  'Dramatic cliffs and stunning sunsets',
  'Santorini captivates visitors with its dramatic cliff-top villages, iconic blue-domed churches, and spectacular sunsets over the Aegean Sea.',
  'April to October',
  '/santorini-cliffs-sunset.png',
  true,
  'Mediterranean climate with hot, dry summers (25-35°C) and mild winters (10-18°C). Strong winds common, especially in summer.',
  'Ancient Greek heritage with Byzantine influences. Traditional architecture, local wine culture, and archaeological significance.',
  'EU regulations apply. Archaeological sites protected. Building restrictions maintain traditional architecture.',
  'EU citizens: no visa required. Others: Schengen visa may be required for stays over 90 days.',
  'Euro (EUR)',
  '["Greek", "English"]',
  15550,
  90.623,
  '{"lat": 36.3932, "lng": 25.4615}',
  '["/santorini-1.jpg", "/santorini-2.jpg", "/santorini-3.jpg"]',
  NOW(),
  NOW()
);
