-- Adding comprehensive event data with all required fields
INSERT INTO events (
  id, title, description, event_type, start_date, end_date,
  start_time, end_time, location, organizer, ticket_price,
  ticket_url, image_url, featured, island_id, contact_info,
  coordinates, created_at
) VALUES 
(
  gen_random_uuid(),
  'Sunset Beach Yoga',
  'Join us for a peaceful yoga session on pristine white sand beaches as the sun sets over the Indian Ocean. Perfect for all skill levels.',
  'wellness',
  '2025-08-15',
  '2025-08-15',
  '18:00:00',
  '19:30:00',
  'Paradise Beach Resort',
  'Maldives Wellness Center',
  45.00,
  'https://booking.example.com/yoga',
  '/sunset-beach-yoga.png',
  true,
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  '{"phone": "+960-123-4567", "email": "yoga@maldiveswellness.com"}',
  '{"lat": 3.2028, "lng": 73.2207}',
  NOW()
),
(
  gen_random_uuid(),
  'Underwater Snorkeling Adventure',
  'Explore vibrant coral reefs and swim with tropical fish in crystal-clear waters. Equipment and guide included.',
  'adventure',
  '2025-08-20',
  '2025-08-20',
  '09:00:00',
  '12:00:00',
  'Coral Garden Bay',
  'Ocean Adventures Maldives',
  85.00,
  'https://booking.example.com/snorkeling',
  '/underwater-snorkeling.png',
  false,
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  '{"phone": "+960-987-6543", "email": "info@oceanadventures.mv"}',
  '{"lat": 3.1950, "lng": 73.2150}',
  NOW()
),
(
  gen_random_uuid(),
  'Traditional Island Cooking Class',
  'Learn to prepare authentic Polynesian dishes using local ingredients and traditional cooking methods.',
  'cultural',
  '2025-08-25',
  '2025-08-25',
  '14:00:00',
  '17:00:00',
  'Cultural Center Vaitape',
  'Bora Bora Cultural Association',
  120.00,
  'https://booking.example.com/cooking',
  '/island-cooking-class.png',
  false,
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  '{"phone": "+689-67-12-34", "email": "culture@borabora.pf"}',
  '{"lat": -16.5004, "lng": -151.7415}',
  NOW()
),
(
  gen_random_uuid(),
  'Volcano Hiking Expedition',
  'Challenging hike to ancient volcanic craters with breathtaking views of the Aegean Sea and neighboring islands.',
  'adventure',
  '2025-09-01',
  '2025-09-01',
  '06:00:00',
  '11:00:00',
  'Fira Hiking Trail',
  'Santorini Adventure Tours',
  65.00,
  'https://booking.example.com/hiking',
  '/volcano-hiking-expedition.png',
  false,
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  '{"phone": "+30-22860-12345", "email": "hike@santorini-tours.gr"}',
  '{"lat": 36.4161, "lng": 25.4324}',
  NOW()
),
(
  gen_random_uuid(),
  'Luxury Catamaran Sunset Cruise',
  'Sail around the lagoon on a luxury catamaran while enjoying champagne and canapés as the sun sets.',
  'luxury',
  '2025-09-05',
  '2025-09-05',
  '16:30:00',
  '19:30:00',
  'Vaitape Marina',
  'Polynesian Luxury Cruises',
  180.00,
  'https://booking.example.com/cruise',
  '/luxury-catamaran-cruise.png',
  true,
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  '{"phone": "+689-67-56-78", "email": "cruise@polynesian-luxury.pf"}',
  '{"lat": -16.5138, "lng": -151.7513}',
  NOW()
),
(
  gen_random_uuid(),
  'Marine Life Photography Workshop',
  'Professional underwater photography workshop with expert guidance and equipment rental included.',
  'educational',
  '2025-09-10',
  '2025-09-10',
  '08:00:00',
  '16:00:00',
  'Oia Photography Studio',
  'Aegean Photo Academy',
  150.00,
  'https://booking.example.com/photography',
  '/underwater-marine-life-photography.png',
  false,
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  '{"phone": "+30-22860-98765", "email": "photo@aegean-academy.gr"}',
  '{"lat": 36.4618, "lng": 25.3753}',
  NOW()
);
