-- Adding comprehensive hotel data with all required fields
INSERT INTO hotels (
  id, name, description, star_rating, rating, review_count,
  price_range, booking_url, website_url, phone, email,
  address, image_url, amenities, room_types, gallery_images,
  island_id, coordinates, affiliate_id, created_at
) VALUES 
(
  gen_random_uuid(),
  'Paradise Overwater Resort',
  'Luxury overwater bungalows with direct lagoon access, private decks, and world-class spa facilities.',
  5,
  4.8,
  1247,
  '$800-2000',
  'https://booking.example.com/paradise-resort',
  'https://paradise-resort.com',
  '+960-123-4567',
  'reservations@paradise-resort.com',
  'North Male Atoll, Maldives',
  '/paradise-overwater-resort.jpg',
  '["Spa", "Private Beach", "Water Sports", "Fine Dining", "Butler Service", "Infinity Pool"]',
  '["Overwater Villa", "Beach Villa", "Presidential Suite"]',
  '["/resort-1.jpg", "/resort-2.jpg", "/resort-3.jpg"]',
  (SELECT id FROM islands WHERE slug = 'maldives-paradise'),
  '{"lat": 3.2028, "lng": 73.2207}',
  'PAR001',
  NOW()
),
(
  gen_random_uuid(),
  'Lagoon View Hotel',
  'Stunning lagoon views with traditional Polynesian architecture and modern luxury amenities.',
  4,
  4.6,
  892,
  '$400-800',
  'https://booking.example.com/lagoon-view',
  'https://lagoon-view-hotel.com',
  '+689-67-12-34',
  'info@lagoon-view.pf',
  'Vaitape, Bora Bora',
  '/lagoon-view-hotel.jpg',
  '["Lagoon Access", "Traditional Spa", "Cultural Shows", "Snorkeling", "Kayaking"]',
  '["Garden Bungalow", "Lagoon View Room", "Overwater Suite"]',
  '["/lagoon-1.jpg", "/lagoon-2.jpg", "/lagoon-3.jpg"]',
  (SELECT id FROM islands WHERE slug = 'bora-bora-lagoon'),
  '{"lat": -16.5004, "lng": -151.7415}',
  'LAG001',
  NOW()
),
(
  gen_random_uuid(),
  'Cliffside Luxury Hotel',
  'Perched on dramatic cliffs with panoramic Aegean Sea views and infinity pools.',
  5,
  4.9,
  1456,
  '$600-1500',
  'https://booking.example.com/cliffside-luxury',
  'https://cliffside-luxury.gr',
  '+30-22860-12345',
  'reservations@cliffside-luxury.gr',
  'Oia, Santorini',
  '/cliffside-luxury-hotel.jpg',
  '["Infinity Pool", "Spa", "Fine Dining", "Wine Cellar", "Helicopter Pad", "Private Beach Access"]',
  '["Cliff Suite", "Caldera View Room", "Presidential Villa"]',
  '["/cliff-1.jpg", "/cliff-2.jpg", "/cliff-3.jpg"]',
  (SELECT id FROM islands WHERE slug = 'santorini-cliffs'),
  '{"lat": 36.4618, "lng": 25.3753}',
  'CLI001',
  NOW()
);
